export const ADD_ALL_PROPERTY_RECORDS = "ADD_ALL_PROPERTY_RECORDS";
export const REMOVE_ALL_PROPERTY_RECORDS = "REMOVE_ALL_PROPERTY_RECORDS";
export const ADD_PROPERTY_RECORD = "ADD_PROPERTY_RECORD";
export const EDIT_PROPERTY_RECORD_BY_INDEX = "EDIT_PROPERTY_RECORD_BY_INDEX";
export const REMOVE_PROPERTY_RECORD_BY_INDEX = "REMOVE_PROPERTY_RECORD_BY_INDEX";
