export const ADD_ALL_ADMINS = "ADD_ALL_ADMINS";
export const REMOVE_ALL_ADMINS = "REMOVE_ALL_ADMINS";
export const ADD_ADMIN = "ADD_ADMIN";
export const EDIT_ADMIN = "EDIT_ADMIN";
export const REMOVE_ADMIN_BY_INDEX = "REMOVE_ADMIN_BY_INDEX";