export const SET_AUTH_JWT = "SET_AUTH_JWT";
export const REMOVE_AUTH_JWT = "REMOVE_AUTH_JWT";
export const ADD_CURRENT_ADMIN = "ADD_CURRENT_ADMIN";
export const REMOVE_CURRENT_ADMIN = "REMOVE_CURRENT_ADMIN";
